# Generated by Django 3.1.4 on 2021-01-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analystic', '0003_dataentery_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentery',
            name='infected',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
