# Generated by Django 3.1.4 on 2021-01-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analystic', '0004_auto_20210105_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentery',
            name='infected',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
