# Generated by Django 3.1.4 on 2021-01-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analystic', '0005_auto_20210105_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataentery',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Data Enteries'},
        ),
    ]
