# Generated by Django 3.1.4 on 2021-01-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analystic', '0006_auto_20210105_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataentery',
            options={'ordering': ['created'], 'verbose_name_plural': 'Data Enteries'},
        ),
    ]
